modid = "hex_open_book"
book = "hexcasting:thehexbook"

resource_dirs = [  # top takes priority
    "resources",
    "{$_common.src}/main/resources",
    { path="{$_common.src}/generated/resources", required=false },
    "{$_fabric.src}/main/resources",
    { path="{$_fabric.src}/generated/resources", required=false },
    "{$_forge.src}/main/resources",
    { path="{$_forge.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hex_open_book/_export/generated"

[template]
icon = "{$_common.src}/main/resources/assets/hex_open_book/icon.png"
include = [
    "hex_open_book",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hex Open Book"
author = "sofistico"
show_landing_text = false

[extra.hexcasting]
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='(?P<is_per_world>make|makePerWorld)\("(?P<name>[^"]+)",\s*HexDir\.(?P<startdir>\w+),\s*"(?P<signature>[qweasd]+)"' }
_per_world_value = "makePerWorld"

[[extra.hexcasting.pattern_stubs]]
path = "{$_common.kotlin}/registry/HexOpenBookActions.kt"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

# platforms

[_common]
src = "../common/src"
java = "{src}/main/java/io/github/sofistico/hex_open_book"
kotlin = "{src}/main/kotlin/io/github/sofistico/hex_open_book"

[_fabric]
src = "../fabric/src"
java = "{src}/main/java/io/github/sofistico/hex_open_book/fabric"
kotlin = "{src}/main/kotlin/io/github/sofistico/hex_open_book/fabric"

[_forge]
src = "../forge/src"
java = "{src}/main/java/io/github/sofistico/hex_open_book/forge"
kotlin = "{src}/main/kotlin/io/github/sofistico/hex_open_book/forge"
